[project]
name = "pyhep-talk"
version = "0.1.0"
description = "ML Game Up - PyHEP Talk"
channels = ["conda-forge", "pytorch"]

[tasks]
start = "jupyter notebook"

[dependencies]
python = ">=3.11,<3.13"
# Core ML Frameworks
pytorch = { version = ">=2.0.0", channel = "pytorch" }
scikit-learn = ">=1.3.0"
numpy = ">=1.24.0"
pandas = ">=2.0.0"
xgboost = ">=2.0.0"
# HEP-ML Bridge Tools
awkward = ">=2.4.0"
uproot = ">=5.1.0"
# Jupyter & Presentation
jupyter = ">=1.0.0"
ipykernel = ">=6.25.0"
matplotlib = ">=3.7.0"
RISE = ">=5.7.0"
# Development tools
pytest = ">=7.4.0"
ruff = ">=0.0.290"
black = ">=23.7.0"
